# Generated by Django 4.2.5 on 2024-09-13 15:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default=uuid.UUID('fceb586b-35ae-45e5-b220-d15185f35bd5'), primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(default=uuid.UUID('bcfef8b1-d2ba-400e-9200-efe6886454cb'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('IE', ''), ('LLC', 'Limited Liability Company'), ('JSC', 'Joint-stock company ')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('bidReviewId', models.CharField(default=uuid.UUID('83838223-ed0b-4b3d-a553-c1ece2b7e9ea'), primary_key=True, serialize=False)),
                ('bidReviewDescription', models.TextField(max_length=1000)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenders',
            fields=[
                ('tenderId', models.CharField(default=uuid.UUID('b1c6a1ca-b860-4b10-ad88-25532ebee205'), primary_key=True, serialize=False)),
                ('tenderName', models.CharField(max_length=100)),
                ('tenderDescription', models.TextField(max_length=500)),
                ('tenderServiceType', models.CharField(choices=[('Construction', 'Строительство'), ('Delivery', 'Доставка'), ('Manufacture', 'Производство')], max_length=30)),
                ('tenderStatus', models.CharField(choices=[('Created', 'Создан'), ('Published', 'Опубликован'), ('Closed', 'Закрыт')], max_length=30)),
                ('tenderVersion', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('creatorUsername', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationResponsible',
            fields=[
                ('id', models.CharField(default=uuid.UUID('f04817a5-5dde-46ec-9717-e3f8df60eba0'), primary_key=True, serialize=False)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.organization')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('bidId', models.CharField(default=uuid.UUID('560bcb44-2821-4dee-bf24-8615653af645'), primary_key=True, serialize=False)),
                ('bidName', models.CharField(max_length=100)),
                ('bidDescription', models.TextField(max_length=500)),
                ('bidStatus', models.CharField(choices=[('Created', 'Создано'), ('Published', 'Опубликовано'), ('Canceled', 'Закрыто')], max_length=30)),
                ('bidAuthorType', models.CharField(choices=[('Organization', 'Организация'), ('User', 'Пользователь')], max_length=30)),
                ('bidVersion', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('bidDecision', models.CharField(choices=[('Approved', 'Одобрено'), ('Rejected', 'Отклонено')], max_length=30)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('bidAuthorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.employee')),
                ('organizationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.organization')),
                ('tenderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.tenders')),
            ],
        ),
    ]
