# Generated by Django 4.2.5 on 2024-09-13 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidId',
            field=models.CharField(default=uuid.UUID('22d38bac-f1a5-482c-8d67-cbf5209d5a53'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default=uuid.UUID('bc3d9958-a755-44dd-a826-70246265490a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default=uuid.UUID('289bdad7-8664-455c-a9e3-2c74795fb63f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organizationresponsible',
            name='id',
            field=models.CharField(default=uuid.UUID('bed29866-2650-4eb7-9e85-a2ff135c1954'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='bidReviewId',
            field=models.CharField(default=uuid.UUID('c2a291f2-125c-4b1f-a835-4822efdabf3e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='tenderId',
            field=models.CharField(default=uuid.UUID('dbd3173a-790f-4ea3-b88c-ef3dcccce4d5'), primary_key=True, serialize=False),
        ),
    ]
