# Generated by Django 4.2.5 on 2024-09-13 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_alter_bids_bidid_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidId',
            field=models.CharField(default=uuid.UUID('96b0f53a-283a-413b-a8ab-8b1cfbdc4ef3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default=uuid.UUID('a128bad6-1fb7-4c8e-84ba-51e262774ede'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default=uuid.UUID('02d0bda2-c279-414c-897c-3af2b68f272e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organizationresponsible',
            name='id',
            field=models.CharField(default=uuid.UUID('38865394-dd83-46b5-8074-052c193fc344'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='bidReviewId',
            field=models.CharField(default=uuid.UUID('108e6237-75a4-41fe-b58f-5f9962eda5dc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='tenderId',
            field=models.CharField(default=uuid.UUID('4ee649d7-71e3-4240-9d9e-a96f6d804f80'), primary_key=True, serialize=False),
        ),
    ]
