# Generated by Django 4.2.5 on 2024-09-13 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_alter_bids_bidid_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidId',
            field=models.CharField(default=uuid.UUID('e95600d9-59fd-466a-9c3e-455c7519a862'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default=uuid.UUID('beb8e506-3bd9-4d5a-9f64-10b941909bf3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default=uuid.UUID('53fac29e-5d84-4217-b936-a819ab14ff66'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organizationresponsible',
            name='id',
            field=models.CharField(default=uuid.UUID('6d696dfb-ade5-4659-bbbb-9108b34bc900'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='bidReviewId',
            field=models.CharField(default=uuid.UUID('a85bce0f-fb86-4694-8325-6f4147d0d8a7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='tenderId',
            field=models.CharField(default=uuid.UUID('88f71125-8535-4115-a13a-0ad1d5f0f9f3'), primary_key=True, serialize=False),
        ),
    ]
